### PR TITLE
Fixed to pass the flake8

### PR DESCRIPTION
**Pull request by spikeekips**
### Background
flake8 was failed, so we need to fix it.

### Solution
Just clean up the code :)

### CODE REVIEW

**Comment by outsideris** [comment]
It still failed because of `./scripts/run-client.py:2:1: F401 'random' imported but unused`.

**Comment by spikeekips** [comment]
@outsideris Sorry, I missed that. I already updated.

**Comment by outsideris** [comment]
Please ignore build failed for this PR. The failure is not related to this PR.
It will be addressed in #10 .

**Review by outsideris — APPROVED** [review]

**Comment by leejames00** [comment]
LGTM :)

**Review by leejames00 — APPROVED** [review]

**Pull request merged**
